# Generated by Django 2.1.7 on 2019-03-29 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romma', '0002_auto_20190329_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='end_at',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 21, 36, 2, 369137)),
        ),
        migrations.AlterField(
            model_name='buy',
            name='started_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
