# Generated by Django 2.1.7 on 2019-03-29 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romma', '0003_auto_20190329_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='end_at',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 21, 47, 9, 306343)),
        ),
    ]
