# Generated by Django 2.1.7 on 2019-03-29 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romma', '0006_auto_20190329_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='end_at',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 22, 6, 51, 257923)),
        ),
    ]
