# Generated by Django 2.1.7 on 2019-03-31 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romma', '0007_auto_20190329_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 12, 44, 32, 936217)),
        ),
        migrations.AlterField(
            model_name='buy',
            name='month_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
