# Generated by Django 2.1.7 on 2019-04-18 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romma', '0009_auto_20190401_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='year_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buy',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 13, 4, 7, 660605)),
        ),
        migrations.AlterField(
            model_name='buy',
            name='month_plan',
            field=models.BooleanField(default=False),
        ),
    ]
