# Generated by Django 2.1.7 on 2019-04-21 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romma', '0010_auto_20190418_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 15, 34, 52, 589550)),
        ),
    ]
